### ISSUE TITLE
Update to boostrap-loader 2.1.0

### ISSUE THREAD

**Issue by aericson** [vintasoftware/django-react-boilerplate#105]
Bootstrap was mistakenly updated to alpha 6 in PR #101.

Need to wait for bootstrap-loader 2.1.0 release that will support alpha 6.
The bootstrap currently uses bootstrap-loader 2.0.0.

@chocoelho @rsarai

**Comment by aericson** [comment]
bootstrap-loader 2.1.0 was released, should update to it.

**Comment by chocoelho** [comment]
Thanks for the reminder @aericson. This should be fixed by now.
