### ISSUE TITLE
Document how make bundle works

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-react-boilerplate#109]
Many people get confused because `make bundle` never finishes. The README running the project section should mention that this is the expected behavior.

**Comment by aericson** [comment]
Maybe we should call it something else? `make bundle` is miss leading.

Why do we need it anyway? Why not just calling `npm run start` which is the convention in frontend development?

**Comment by filipeximenes** [comment]
That makes sense. @hugobessa also commented about this.
