### ISSUE TITLE
Update to webpack v3

### ISSUE THREAD

**Issue by chocoelho** [vintasoftware/django-react-boilerplate#110]
It was announced that Webpack 3 was released[1]. We are currently supporting v2.2.1 according to our `package.json` file[2]. Webpack 3 is already stable, so we need to check if upgrading is possible now and if not we need to track what other necessary steps are required to update this package.

[1] https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b
[2] https://github.com/vintasoftware/django-react-boilerplate/blob/269bc469210389d8d2701dc015e91841a2750849/package.json#L42

**Comment by aericson** [comment]
Blocked by:
https://github.com/webpack/webpack-dev-server/pull/946
https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/540

**Comment by chocoelho** [comment]
@aericson both PRs are now merged :smile:
