### ISSUE TITLE
Manual checklist when creating project

### ISSUE THREAD

**Issue by aericson** [vintasoftware/django-react-boilerplate#115]
Some things break too easily and are hard to be spotted ie: hot reloader and auto-prefixer.

What do you guys think of having something like this:
![screen shot 2017-06-28 at 04 50 44](https://user-images.githubusercontent.com/692542/27626197-8f6780ae-5bbd-11e7-9ea7-a1db62b38811.png)

**Comment by filipeximenes** [comment]
@aericson great idea! Really like it!

**Comment by chocoelho** [comment]
@aericson It'd be good to inform that something might not be working properly as well, no? Otherwise, e.g. if items 3 and 4 don't show up, one may think everything is okay.

**Comment by aericson** [comment]
@chocoelho 3 and 4 will show a negative message if their test fails.
