### ISSUE TITLE
Is boilerplate release broken?

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#123]
Looks like the Ci for `boilerplate-release` branch wasn't running. See, it has only "skipped": https://circleci.com/gh/vintasoftware/django-react-boilerplate/tree/boilerplate-release

I ran it manually and it failed: https://circleci.com/gh/vintasoftware/django-react-boilerplate/110

Can someone check this? @rsarai @filipeximenes @lucabezerra

**Comment by filipeximenes** [comment]
@fjsj I believe that boilerplate-release is not meant to pass. It neither specifies `requirements.txt` or `proj_circle.yml` has details on how to install from `requirements-to-freeze.txt` (because we don't want this on a real project)

**Comment by fjsj** [comment]
ok, probably that's why @aericson made it to be skipped. thanks!

**Comment by aericson** [comment]
Yes.

The `boilerplate-release` branch is generated automatically (by master's `circle.yml`) on top of master. The only difference is that it replaces the `circle.yml` file to the one the template uses.

Since it's a template it won't pass.
