### ISSUE TITLE
Update to Bootstrap 4 beta

### ISSUE THREAD

**Issue by chocoelho** [vintasoftware/django-react-boilerplate#125]
Right now, we're using Bootstrap 4 alpha 6. We need to consider what changes are required to do this upgrade and/or track what can be a blocker.

**Comment by aericson** [comment]
Related: https://github.com/shakacode/bootstrap-loader/issues/315

**Comment by chocoelho** [comment]
It seems that issue is fixed, I think we can start to consider the upgrade of both `bootstrap` and `bootstrap-loader`.
