### ISSUE TITLE
Use a faster password hasher as 'django.contrib.auth.hashers.MD5PasswordHasher' to speed-up tests

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#128]
Django own tests do this: https://github.com/django/django/blob/master/tests/test_sqlite.py

**Comment by lucabezerra** [comment]
@fjsj This seems to be done already, isn't it? :)

**Comment by fjsj** [comment]
yes, thanks @lucabezerra !
