### ISSUE TITLE
Use pip-tools

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#135]
https://github.com/jazzband/pip-tools
4 minute talk explaining why: https://www.youtube.com/watch?v=LAig6s9Hkj0

**Comment by aericson** [comment]
Pipenv is really nice, might be a good option too.

**Comment by aericson** [comment]
https://github.com/kennethreitz/pipenv

**Comment by chocoelho** [comment]
IMO, we should be using Pipenv. It's a really simple tool and it makes it even easier to setup the boilerplate.

**Comment by aericson** [comment]
Yes, I've been using it in other projects it's really great. And heroku is compatible with it. Don't even need to create a requirements.txt it will use the `PIpfile` out of the box.

**Comment by hugobessa** [comment]
Pipenv is beautiful! I made the migration in a branch, but I'm still having issues with the CI. I will PR soon!

**Comment by aericson** [comment]
@hugobessa just a tip. You don't need to create a virtualenv on the CI. You can just use `pip install pipenv`. Then install the dependencies with `pipenv install` (this will create a virtual env) then run every command that needs python with `pipenv run python ...`

**Comment by hugobessa** [comment]
I think maybe with the virtualenv is better, because pipenv automatically detects the active virtualenv it and install everything on it. So there's no need to prefix the commands.

But problem I'm having now is not with pipenv really. The current build in master is broken. The details are on #156.

**Comment by aericson** [comment]
That's odd, the PR @chocoelho  just made is building fine. https://circleci.com/gh/vintasoftware/django-react-boilerplate/175

**Comment by aericson** [comment]
Oh, you mean the `proj_circle.yml`. Yeah, that one is a pain to test. Good luck ;)

**Comment by chocoelho** [comment]
@hugobessa is something like https://github.com/TheRealJoeLinux/circlecli useful to check this?

**Comment by hugobessa** [comment]
hmm, this could help, @chocoelho, but the biggest problem is to wait the build run every change we make in the circleci.yml :weary:
