### ISSUE TITLE
Add migrate to post_compile

### ISSUE THREAD

**Issue by aericson** [vintasoftware/django-react-boilerplate#14]

**Comment by laisvarejao** [comment]
@aericson we've been setting the migrate along with the continuous deployment, so we can enable the maintenance mode:

```  
- heroku maintenance:on -a {{project_name}}
- heroku run python manage.py migrate -a {{project_name}}
- heroku maintenance:off -a {{project_name}}
```

What are your thoughts on this?

**Comment by aericson** [comment]
this was already added to https://github.com/vintasoftware/django-react-boilerplate/blob/master/bin/post_compile#L15-L18

**Comment by aericson** [comment]
@laisvarejao probably the approach you mentioned is better if we can add a check to $AUTO_MIGRATE.

**Comment by aericson** [comment]
Closing it, create a new issue to modify it if you think it's worth the trouble.
