### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by laisvarejao** [vintasoftware/django-react-boilerplate#142]
The step below from the [Project Bootstrap](https://github.com/vintasoftware/django-react-boilerplate#project-bootstrap-) is not required, because we're already using the fixed version of **bootstrap-loader**:

> - [ ] Remove the ^ from "bootstrap-loader": "^2.1.0" in the package.json file. bootstrap-loader 2.2 breaks semver by breaking support for 4.0.0-alpha.6. This step will be removed when we update to bootstrap beta version.

*from the package.json:*
```json
    "bootstrap-loader": "2.1.0",
```

**Comment by aericson** [comment]
Hey Lais!

When we run `npm update --save` it will add the `ˆ`. This is why we need to manually remove it.

I just tried this with a new project.

**Comment by aericson** [comment]
Even had to change the `circle.yml` to build properly. See: #133 #134

**Comment by laisvarejao** [comment]
Humm, got it! Will close this issue
