### ISSUE TITLE
Use greenkeeper to keep npm dependencies up to date

### ISSUE THREAD

**Issue by sloria** [vintasoftware/django-react-boilerplate#145]
[Greenkeeper](https://greenkeeper.io/) is a service that automatically sends PRs to keep your npm dependencies up-to-date. It is a *huge* time-saver for projects like this, and it's free for OSS projects.

Note: I am not affiliated with Greenkeeper in any way. It's just been a very useful tool for me in my projects.

**Comment by vanessa** [comment]
Done in #204.
