### ISSUE TITLE
Extract Contributing section into its own file

### ISSUE THREAD

**Issue by chocoelho** [vintasoftware/django-react-boilerplate#150]
We can take advantage of having a separate CONTRIBUTING file, as shown in https://help.github.com/articles/setting-guidelines-for-repository-contributors/.

This way, it's visible whenever opening PRs or new issues.

**Comment by chocoelho** [comment]
A good idea is to integrate what was created by @lucabezerra into CONTRIBUTING.md

See: http://pullrequests.devchecklists.com/

**Comment by vanessa** [comment]
Was this done in #199?

**Comment by chocoelho** [comment]
Yes, thought the PR had the `resolve` clause in it. Thanks for noticing that. :call_me_hand:
