### ISSUE TITLE
Add CELERY_TIMEZONE = TIME_ZONE in settings/base.py

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#152]

**Comment by lucabezerra** [comment]
@andersonresende  Are you still doing this? Is this issue still valid?

**Comment by SEdilson** [comment]
Hey guys, is anyone working on this issue? If not I'd like to work on it.

**Comment by fjsj** [comment]
@SEdilson could you please check if it's already fixed? If not, we're happy to review a PR on this. Thank you!

**Comment by jhgv** [comment]
Closed by #419
