### ISSUE TITLE
Add CELERY_ACKS_LATE = True to settings/base.py

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#153]

**Comment by filipeximenes** [comment]
This might be a dangerous default for a boilerplate

**Comment by fjsj** [comment]
I think it's more dangerous to lose tasks. Tasks should be idempotent.

We need this or something clear on README saying you should activate that.

**Comment by filipeximenes** [comment]
I'm pro the README approach. This is a public boilerplate and it's probably being used by beginners.

**Comment by andersonresende** [comment]
do you guys really think that the Boilerplate should concern about it?

**Comment by fjsj** [comment]
Yes. The project you're working on didn't have acks late until I fixed.
Maybe because the boilerplate was silent about it.

**Comment by andersonresende** [comment]
If we want a simple boilerplate to start a project with Django and React adding a lot of stuff is just overweelming it. I really don't know if is good put everything that we like as libs or even configurations.

**Comment by fjsj** [comment]
Originally this was also a Celery boilerplate. If we're keeping Celery, IMO
we should inform about its behavior.

**Comment by andersonresende** [comment]
Ok, I got it.

**Comment by lucabezerra** [comment]
@andersonresende  Are you still doing this? Is this issue still valid?

**Comment by fjsj** [comment]
We changed our philosophy. The boilerplate should be more opinionated. So yes, CELERY_ACKS_LATE must be true @lucabezerra

**Comment by lucabezerra** [comment]
@fjsj Cool, created a PR for it, hope it helps :)
