### ISSUE TITLE
It's very easy for the local.py.example to get outdated

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-react-boilerplate#16]
Instead of local.py.example lets have a `local.py` and a `base_local.py`. `base_local.py` has everything we currently put on `local.py.example` while `local.py` will import everything from `base_local`. 
README should have instructions for the developer to create `local.py` and import from `base_local.py`

**Comment by andersonresende** [comment]
@aericson @fjsj any opinion?

**Comment by fjsj** [comment]
looks best IMO
