### ISSUE TITLE
.bootstraprc Webpack loaders order is incorrect

### ISSUE THREAD

**Issue by laisvarejao** [vintasoftware/django-react-boilerplate#160]
Right now the configuration has `- postcss` after `- sass`. However, this way the autoprefixer doesn't work. The correct order is:

```
# Webpack loaders, order matters
styleLoaders:
  - style-loader
  - css-loader
  - postcss-loader
  - sass-loader
```

**Comment by chocoelho** [comment]
@laisvarejao did you check https://github.com/shakacode/bootstrap-loader/pull/316#issuecomment-322984785? Here it was said why that change was made.

**Comment by chocoelho** [comment]
Also, shouldn't they have the `-loader` suffix?

**Comment by laisvarejao** [comment]
@chocoelho yes, I believe you're correct about the `-loader`suffix.  And yes, I saw the discussion about the why the order matters. However, when testing here, setting the `postcss-loader` below the `sass-loader` does not autoprefix the properties. 

I don't know if another configuration is wrong :(

**Comment by lucabezerra** [comment]
@laisvarejao @chocoelho is this still relevant?
