### ISSUE TITLE
Use other linters-wrapper instead of prospector

### ISSUE THREAD

**Issue by hugobessa** [vintasoftware/django-react-boilerplate#165]
Prospector is out of date and not being well maintained anymore, so we should consider replacing it with other linters-wrapper like coala (https://github.com/coala/coala) or pylama (https://github.com/klen/pylama).

Use this repo (https://github.com/vintasoftware/python-linters-and-code-analysis) as reference.

**Comment by chocoelho** [comment]
Another option would be to use our prospector fork and maintain it since prospector is still widely used.

**Comment by hugobessa** [comment]
When fixing this issue we have to remember to unlock pylint and astroid versions on Pipfile

**Comment by hugobessa** [comment]
Yes!

**Comment by hugobessa** [comment]
Yes!
