### ISSUE TITLE
Upgrade to Django 2.0

### ISSUE THREAD

**Issue by aericson** [vintasoftware/django-react-boilerplate#167]
Some problems mentioned here: https://github.com/vintasoftware/django-react-boilerplate/issues/166

**Comment by chocoelho** [comment]
I just read the traceback described in these issues. Problems are on https://github.com/fixmydjango/fixmydjango-lib. https://github.com/ierror/django-js-reverse fixed the issue on 0.8.1.

**Comment by andersonresende** [comment]
is there anyone working on it? @aericson @chocoelho

**Comment by aericson** [comment]
Dependencies @chocoelho mentioned need to be fixed first.

**Comment by andersonresende** [comment]
I got it, I am gonna check what I can do on the dependencies.

**Comment by andersonresende** [comment]
I think at least we should put a note in the Readme, saying that is possible run over Django 2.0 if you remove `fixmydjango settings`.  In order to prevent more issues like the ones reported previously. any thoughts about it? @aericson @chocoelho

**Comment by aericson** [comment]
IMO we should just focus on moving to 2.0 as soon as we can. If there are other problems with 2.0 we won't be able to fix anyway, better say we support 2.0 when we actually do it.

**Comment by chocoelho** [comment]
I'm with @aericson on this one. fixmydjango has been pinned to use 
Django versions < 2.0, so we can contribute to the library adding this 
support. It's good to check dependencies on Pipfile if there's anything 
there that doesn't support Django 2.0 yet.

**Comment by andersonresende** [comment]
The problem is, we can't wait for all the libs to be fixed. For me, it's more important have the boilerplate working with the latest Django version, than with the libs that you can just not use.

**Comment by andersonresende** [comment]
@fjsj what do you think about it?

**Comment by chocoelho** [comment]
"For me, it's more important have the boilerplate working with the 
latest Django version"


That's even another reason to check the libraries we use if they are 
already supporting Django >= 2.0.

**Comment by andersonresende** [comment]
Yeah, But we know that fixmydjango is not working, and there is a guy saying that is gonna fix it. The problem is that: either we wait to fix all the libs or we can move to Django 2.0 and let everyone know that some libs are not working in this version. The question is, what do we do now?

**Comment by chocoelho** [comment]
I think we should take the same approach we do for frontend libs. Just move to the latest version once related dependencies support the version migration we want to do as well. It's been working fine for Bootstrap and Webpack, so we should use the same approach for Django.

**Comment by andersonresende** [comment]
@chocoelho I got it. Thanks

**Comment by ACPK** [comment]
@aericson @vintasoftware - Seeing that the issue is now closed, what is the progress of upgrading the app to Django 2.0?

**Comment by chocoelho** [comment]
@ACPK as of now, I'm working on migrating fixmydjango-lib to Django 2.0. After that, we should be good to go on officially supporting Django 2.0 on the boilerplate.
