### ISSUE TITLE
Change celery beat scheduler to avoid using filesystem  

### ISSUE THREAD

**Issue by hugobessa** [vintasoftware/django-react-boilerplate#171]
The default celery beat scheduler uses a file database to manage the periodic tasks. This is not safe in heroku file system so we should use an alternative.

Some alternatives are:
* https://github.com/sibson/redbeat
* https://github.com/celery/django-celery-beat

**Comment by filipeximenes** [comment]
https://blog.heroku.com/redbeat-celery-beat-scheduler

**Comment by fjsj** [comment]
@rvlb please research on Celery Beat for Heroku, check how our projects are doing
