### ISSUE TITLE
Update Webpack loaders configuration to Webpack 3 standards

### ISSUE THREAD

**Issue by laisvarejao** [vintasoftware/django-react-boilerplate#173]
https://webpack.js.org/concepts/#loaders

**Comment by raj16559** [comment]
did you update your webpack loaders ?

**Comment by chocoelho** [comment]
@laisvarejao is there any other change to the current webpack config? I guess I've already adapted when upgrading our babel version to 7 and webpack to v4.

**Comment by lucabezerra** [comment]
Is this even relevant anymore?
