### ISSUE TITLE
Fix pylint and astroid versions

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-react-boilerplate#186]
Current version specifications are conflicting in pipenv. 
```
astroid = "==1.6.1"
pylint = "==1.8.2"
```
Seems to work but weird to do such a specific pin.

**Comment by hugobessa** [comment]
This was added because prospector deps required versions of astroid and pylint that were breaking our build. They released new versions for both fixing everything. These pins were already removed on #180.
