### ISSUE TITLE
Papertrail alerts

### ISSUE THREAD

**Issue by aericson** [vintasoftware/django-react-boilerplate#20]
Add to README instructions to setup Papertrail alerts.

Examples:

```
Name:Platform errors
Query:
"error code=H" OR "Error R" OR "Error L"
```

```
Name:Request timeout
Query:
code=H12
```

```
Name:Worker errors
Query:
"app/worker" AND ERROR/MainProcess
```

**Comment by filipeximenes** [comment]
The same applies to Papertrail

**Comment by aericson** [comment]
ooops, it was supposed to be papertrail. No idea where I got paperclip from xD

**Comment by hugobessa** [comment]
We're not supporting papertrail anymore as Render.com has its own logs tool.
