### ISSUE TITLE
Consider using black or yapf for Python code formatting

### ISSUE THREAD

**Issue by chocoelho** [vintasoftware/django-react-boilerplate#200]
**Is your feature request related to a problem? Please describe.**
Based on the premise of having an unified code style on projects, it'd be great if we add support to a code formatting tool.

**Describe the solution you'd like**
This can be done either during development by the developers themselves or integrated as a pre-commit hook.

**Describe alternatives you've considered**
There are two popular tools to achieve this:
- [google/yapf](https://github.com/google/yapf)
- [ambv/black](https://github.com/ambv/black)

**Additional context**
At a first glance, seems like the latter is not configurable, while the former is. IMHO, this should be taken into consideration.

**Comment by chocoelho** [comment]
If we go with [google/yapf](https://github.com/google/yapf), I'd suggest start with the following configuration inside `.style.yapf`

```
[style]
based_on_style=pep8
column_limit=100
dedent_closing_brackets=true
```

**Comment by aericson** [comment]
Another point to take into consideration is that black seems to be way more active:

https://github.com/ambv/black/pulse/monthly
https://github.com/google/yapf/pulse/monthly

but guess it might be because black is newer and people are excited about it xD

**Comment by chocoelho** [comment]
Makes sense too @aericson, although yapf is still more popular if we take Stars as a measure for that.

**Comment by rednafi** [comment]
@chocoelho Nope. Not anymore:stuck_out_tongue:

**Comment by vanessa** [comment]
How about we use black which's already well established by now?
