### ISSUE TITLE
Remove UglifyJsPlugin from prod webpack

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-react-boilerplate#207]
**Describe the bug**
Webpack 4 has built in UglifyJsPlugin. Explicitly using the plugin in the configuration will cause it to run twice making the process slower and may lead to bugs (happened to me).

**To Reproduce**
///////////////////

**Expected behavior**
///////////////////

**Screenshots**
///////////////////

**Desktop (please complete the following information):**
///////////////////

**Smartphone (please complete the following information):**
///////////////////

**Additional context**
///////////////////

**Comment by joaopslins** [comment]
@filipeximenes I can't find this plugin on the webpack config files, maybe this issue is solved already?

**Comment by filipeximenes** [comment]
Perhaps it was already fixed
