### ISSUE TITLE
Frontend should be first class citizen

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-react-boilerplate#214]
**Is your feature request related to a problem? Please describe.**
Despite all the importance of the frontend in the project our current structure does not reflects that and it's treated as a second class citizen in the architecture (`assets`). 

**Describe the solution you'd like**
My proposal is that the root of the project should have two folders: `frontend` and `backend`.

**Describe alternatives you've considered**
I did some experimentation here: https://github.com/filipeximenes/first-class-frontend-on-boilerplate and found it an interesting approach. 

**Additional context**
Some possible downsides are that you will need to prefix `manage.py` when running things locally or in heroku (`backend/manage.py ...`), this can be mitigated locally by `cd`ing in the folder.

**Comment by embs** [comment]
Wouldn't a first-class citizen deserve its own git repository? :sweat_smile:

**Comment by filipeximenes** [comment]
Done!
