### ISSUE TITLE
Unable to generate test coverage report

### ISSUE THREAD

**Issue by sohaibfarooqi** [vintasoftware/django-react-boilerplate#242]
**Describe the bug**
[pipenv run coverage xml -O test-reports/results.xml](https://github.com/vintasoftware/django-react-boilerplate/blob/master/proj_circle.yml#L91), throws me an error on Circle CI 2.0(also on my machine) saying:
```
no such option: -O
Use 'coverage help' for help.
```

**To Reproduce**
1. `pipenv run coverage run manage.py test`
2. `npm run test`
3. `pipenv run coverage xml -O test-reports/results.xml`

**Expected behavior**
I expected to generate coverage report under `test-reports/results.xml`

**Desktop (please complete the following information):**
 - OS: mac 10.13.6
 - CircleCI 2.0

**Comment by chocoelho** [comment]
Thanks for reporting that @sohaibfarooqi. This should be fixed by replacing the upper case `O` by a lower case `o`, thus the command shall be `pipenv run coverage xml -o test-reports/results.xml`.

I'll be closing that since it's fixed in `master` branch, but lmk if you need any help with that.
