### ISSUE TITLE
Split the webpack bundle to improve caching

### ISSUE THREAD

**Issue by tcostam** [vintasoftware/django-react-boilerplate#254]
Please consider splitting the webpack bundle using the following strategies:
1. Bundle Splitting
2. Code Splitting

This can improve caching and reduce loadtime.
Please refer to [this article](https://hackernoon.com/the-100-correct-way-to-split-your-chunks-with-webpack-f8a9df5b7758).

**Comment by amandasavluchinske** [comment]
@joaopslins I think you've done this already. Please confirm if so :)

**Comment by joaopslins** [comment]
Not really but this could be done together with #337
