### ISSUE TITLE
react-bootstrap instead of just bootstrap

### ISSUE THREAD

**Issue by elfelround** [vintasoftware/django-react-boilerplate#259]
From the [package.json of installed modules](https://github.com/vintasoftware/django-react-boilerplate/blob/95f789f344e04b56c16da0c9227595b159664547/package.json#L22) I see this is using plain bootstrap,
[    "bootstrap": "^4.1.1",](https://github.com/vintasoftware/django-react-boilerplate/blob/95f789f344e04b56c16da0c9227595b159664547/package.json#L22)
 should't this be using react-bootstrap instead since it collides a lot with react?

Maybe I am wrong and this is actually react-bootstrap?

I tried to see some implementation of bootstrap classes on the test but there was nothing there really I could see to understand this bootstraps implementation. A sample test of bootstrap applications would be interesting to see what sort of bs this is using.

**Comment by elfelround** [comment]
wanted to make sure this only has vanilla bootstrap and not react-bootstrap since bootstrap jquery collides with bootstrap, i found it quite weird it was vanilla so wanted to make sure it isnt imported on some script anywhere else which seems not, so its basically vanilla

**Comment by elfelround** [comment]
even tho react-bootstrap plus bs3 stylesheets is still recommended over bs4

**Comment by lucabezerra** [comment]
@chocoelho @hugobessa What's the final take on this? Should we close the ticket if it's not going to be done?

**Comment by fjsj** [comment]
Yes, we should move to react-bootstrap: @rvlb
