### ISSUE TITLE
Setup frontend test archtecture

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-react-boilerplate#27]

**Comment by filipeximenes** [comment]
Maybe use this: https://github.com/airbnb/enzyme

**Comment by aericson** [comment]
@filipeximenes Not gonna do it anymore?

**Comment by filipeximenes** [comment]
@aericson i think there's not much to do here. We are using `__tests__` folder structure. What do you think  we should do here?

**Comment by aericson** [comment]
I think we could at least:

* Add dependecies to package.json (ie: jest, enzyme).
* Add `npm test` command.
* Add `npm test` to `circle.yml`.
* Add one simple test case to show that test works.

**Comment by filipeximenes** [comment]
@aericson got it! reopening :)
