### ISSUE TITLE
Continuously Integrate Heroku Deployment

### ISSUE THREAD

**Issue by embs** [vintasoftware/django-react-boilerplate#280]
**Is your feature request related to a problem? Please describe.**

Heroku and this project are constantly changing and sometimes changes can brake deployment on Heroku of new apps deriving from django-react-boilerplate. This was experienced at least in

- https://github.com/vintasoftware/django-react-boilerplate/issues/55
- https://github.com/vintasoftware/django-react-boilerplate/issues/279

**Describe the solution you'd like**

Deployment to Heroku to be performed and validated for every PR before it gets merged into master.

**Describe alternatives you've considered**

I can't tell if CircleCI would be capable of accomplishing such a thing but I guess we could use some tool for CI / CD to deploy the example app to Heroku and perform some health check (beyond the ones Heroku already provides, e.g., [this one](https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api#polling-for-setup-status)).

**Additional context**

Related issues:

- https://github.com/vintasoftware/django-react-boilerplate/issues/161
- https://github.com/vintasoftware/django-react-boilerplate/issues/279
- https://github.com/vintasoftware/django-react-boilerplate/issues/13
- https://github.com/vintasoftware/django-react-boilerplate/issues/55

**Comment by hugobessa** [comment]
We're not supporting Heroku anymore, but Render.com instead. I think the same suggestion applies to Render.com, so I've created a new issue for that here #593
