### ISSUE TITLE
Use model-utils Choice for choices

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#289]
https://django-model-utils.readthedocs.io/en/latest/utilities.html#choices

This facilitates to catch old references when changing choices.

**Comment by amandasavluchinske** [comment]
@fjsj Is this still needed? The library seems to be in our requirements from what I've seen.

**Comment by fjsj** [comment]
@amandasavluchinske is it used in any examples in code?

**Comment by amandasavluchinske** [comment]
@fjsj Apparently not

**Comment by fjsj** [comment]
So I guess this more an issue for Vinta Tech Stack product than here.
