### ISSUE TITLE
Get common libs from other Vinta projects and add it here

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#290]

**Comment by fjsj** [comment]
e.g.

https://github.com/j4mie/django-spurl
https://pypi.python.org/pypi/django-widget-tweaks
https://github.com/brack3t/django-braces
https://github.com/carljm/django-model-utils

**Comment by lucabezerra** [comment]
@fjsj Does this mean just adding the packages to the requirements file or actually changing the code to use it? The former is a super quick fix (but also doesn't really add much), but the latter involves going through the whole code and knowing where to use each one of them. If the idea is more towards the latter option, perhaps creating separate tickets for each lib would make this task more feasible?

Asking just for clarity's sake of whoever gets this one :)

**Comment by fjsj** [comment]
Yes for the latter @lucabezerra 
But it's difficult to use those libs in a boilerplate project. Perhaps we need an example project that uses this boilerplate, and then on it we should use this libs. It's a larger issue.
