### ISSUE TITLE
Add Deployment section on readme

### ISSUE THREAD

**Issue by joaopslins** [vintasoftware/django-react-boilerplate#296]
When we look to the evolution of the boilerplate project, one thing that is lacking is a section related to Deployment. Currently we actually do have a webpack production configuration and a django production settings, but we do not have anything directly related to the deployment, except for a mention to the Heroku button. No builds, no environment configurations, no guides. A few issues already popped up but a final solution never came up.

Of course the focus here is not to instruct people how to deploy to the cloud, but the configurations needed when setting up a production environment using this boilerplate.

Related issues:
#161 - Explain manual deployment to Heroku
#280 - Continuously Integrate Heroku Deployment
#257 - Use sourcemap to Sentry
#293 - GTM issue

Problem to be solved:
If I want to configure tool X when Deploying from boilerplate, where should I set these keys?

What to consider:
- Define the scope of deployments. Should we consider only Heroku? AWS? Instruct in a more generic way?
- Integrations with 3rd party tools, what is interesting for the boilerplate to have? E.g. Sentry, GTM, etc
- Maybe not everything should be enabled for every boilerplate project. Should we have some kind of toggle, so we can choose the features we want on the template? If we want the boilerplate to be as complete as possible, but keep it flexible, this needs to have some thought.

**Comment by fjsj** [comment]
Bring this to weekly meeting please
