### ISSUE TITLE
npm install --save fails on Debian 9 due to node-sass being outdated

### ISSUE THREAD

**Issue by adjscent** [vintasoftware/django-react-boilerplate#317]
**Describe the bug**
Unable to do npm install --save as described in the installation steps.

**To Reproduce**
1.  Follow installation steps on Debian 9
2.  npm install --save
3. Compilation fails on node-sass

**Additional context**
Fix via updating node-sass package to latest node-sass@4.12.0.
- npm install node-sass@latest
- manual edit of the package.json

**Comment by joaopslins** [comment]
Hi @adjscent, thanks for submitting this issue.

We tried to reproduce this issue using docker: `docker run -it debian:9`, using Node 11.15 and Npm 6.7.0, we ran `npm install --save` and `npm run build` and no errors were found. Do you have more info about this error? Or an issue referring to this elsewhere?

I'll give a look into updating the package.json dependencies anyway, some of them are outdated.

**Comment by adjscent** [comment]
Hi @joaopslins, sorry for the late reply. Time zone issues.

The only other information on the virtual machine I am using is just:

```
gcc version 6.3.0 
```

This is a fresh install of Debian 9 from the iso.

**Comment by adjscent** [comment]
The error message that popped up in the ```npm install --save``` was something to do with node-sass conflicting with v8 code. Unfortunately, there was too much gibberish in the log that I assumed the node-sass is not compiling correctly and updated the package.
