### ISSUE TITLE
JS dependencies update / cleanup

### ISSUE THREAD

**Issue by joaopslins** [vintasoftware/django-react-boilerplate#335]
**Description:**
Coming together with our upcoming stack list, I think it's a good idea to update our dependencies with the new patterns we've developed recently. Also clean up dependencies we think to be unimportant on the boilerplate.

**Comment by joaopslins** [comment]
@filipeximenes @victorfsf Looking forward for your opinions about this.

**Comment by filipeximenes** [comment]
Yes, we need to get rid of all that bootstrap ans scss stuff

**Comment by vanessa** [comment]
So can #259 be closed?

**Comment by joaopslins** [comment]
I don't know, IMHO we should promote more recent technologies, and avoid specific UI kits. Things like [Styled-components](https://styled-components.com/) / [styled-sytem](https://styled-system.com/) or [tailwind css](https://tailwindcss.com/) comes to mind

**Comment by vanessa** [comment]
There are some warnings that we could address as well.
```
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
```

**Comment by jhgv** [comment]
@joaopslins This #451 is related to this one, right?

**Comment by joaopslins** [comment]
Maybe, they could be tackled together or not

**Comment by fjsj** [comment]
I don't think this project should get rid of bootstrap, as it's one of it's main objectives: to connect React, Bootstrap, and Django. Closing this issue.

**Comment by filipeximenes** [comment]
@fjsj should we consider https://react-bootstrap.github.io/ instead of using css classes directly?

**Comment by fjsj** [comment]
yes, we'll be using it! https://github.com/vintasoftware/django-react-boilerplate/issues/259 is assigned to Renato.
