### ISSUE TITLE
Revisit webpack configuration

### ISSUE THREAD

**Issue by joaopslins** [vintasoftware/django-react-boilerplate#337]
Update webpack configuration, optimize it for development and production, look for good practices and incorporate them to our configuration.

**Comment by joaopslins** [comment]
Related #350

**Comment by joaopslins** [comment]
Remove jquery entrypoint

**Comment by fjsj** [comment]
did you ever finish this issue @joaopslins ?

**Comment by joaopslins** [comment]
Not yet

**Comment by lucabezerra** [comment]
Is this also related to https://github.com/vintasoftware/django-react-boilerplate/issues/173?

**Comment by lucabezerra** [comment]
Also https://github.com/vintasoftware/django-react-boilerplate/issues/160

**Comment by joaopslins** [comment]
Not the main issue that I was thinking of when I opened this issue but I think it's related.
