### ISSUE TITLE
Create command to cleanup example code

### ISSUE THREAD

**Issue by joaopslins** [vintasoftware/django-react-boilerplate#339]
As suggested by @vanessa , it would be nice if the boilerplate had a command to delete the example code

**Comment by isabarros** [comment]
Is this still needed @joaopslins ? :)

**Comment by joaopslins** [comment]
@isabarros It was just an idea. Had a chat with @vanessa at the time because she have used the boilerplate for a few projects and she had to delete a few files everytime.

Also because we had an idea of expanding the example code on the boilerplate with some practices that we use at Vinta, so it made sense at the time.

**Comment by fjsj** [comment]
@jhgv create a Makefile command for that
