### ISSUE TITLE
React hot reload is not working

### ISSUE THREAD

**Issue by joaopslins** [vintasoftware/django-react-boilerplate#350]
**Describe the bug**
React hot reload is not working on boilerplate

**To Reproduce**
1. Follow all the steps on the boilerplate
2. Run the project
3. Open localhost:8000
4. Change code and see that the page is refreshing

Also there are a lot of 404 errors, this probably have something with the django webpack loader

**Expected behavior**
It should work

**Screenshots**
![image](https://user-images.githubusercontent.com/15643533/61498886-818c6e80-a99b-11e9-8000-63ed7063f909.png)

**Comment by joaopslins** [comment]
Actually the hot reload is working, but there is this 404 error for sockjs-node. To make this error disappear, just add `port: 3000` to `server.js` devpack hot module settings, but this breaks the hot reload, there is a 404 on `hot-update.json` file.

This needs further investigation, probably the solution is to just have one entry point instead of two. There is no reason to have a separate entrypoint for jquery

**Comment by fjsj** [comment]
superseded by #337

**Comment by Buuntu** [comment]
Was this issue ever fixed or is there a workaround in the meantime?

**Comment by jhgv** [comment]
Hi @Buuntu. The is a PR (#427) that will fix it. It should be merged by this week.
