### ISSUE TITLE
Add default config to prevent session cookie issue

### ISSUE THREAD

**Issue by rsarai** [vintasoftware/django-react-boilerplate#367]
Defaults for below prevent the CSRF or session cookie from being sent in cross-site requests. Options are 'Lax' (default), 'Strict', and None. Those must be None due to a bug in Safari 12: 
- https://bugs.webkit.org/show_bug.cgi?id=188165
- https://www.calazan.com/django-21-samesite-cookie-issue-with-safari-12/
- https://github.com/axios/axios/issues/1661#issuecomment-463468120

```python
CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_SAMESITE = None
```

**Comment by SEdilson** [comment]
Hey guys, I saw this issue hasn't been solved yet. Could I send a PR to be reviewed?

**Comment by rsarai** [comment]
Yes @SEdilson, feel free to open a PR! Please include in a comment near the solution a link to this issue :smiley:
