### ISSUE TITLE
.bootstraprc should point to bootstrap customizations file

### ISSUE THREAD

**Issue by aericson** [vintasoftware/django-react-boilerplate#37]

**Comment by morrme** [comment]
would that be this file? 
https://github.com/vintasoftware/django-react-boilerplate/blob/master/assets/sass/vendor/custom-bootstrap.scss

**Comment by laisvarejao** [comment]
@morrme Yes!

**Comment by morrme** [comment]
@laisvarejao Thanks! i gave it a shot and sent a PR for your team's review :smiley:
