### ISSUE TITLE
Migrate default local database from sqlite to postgres

### ISSUE THREAD

**Issue by joaopslins** [vintasoftware/django-react-boilerplate#371]
Currently, local database by default is sqlite, I think we should move to postgres locally, since it reflects more our stack and workflow. Also because currently when we use the boilerplate for an internal project we need to change this everytime.

Also a description is needed on `README.md`

**Comment by gtsalles** [comment]
This can be done easily with the docker support I'm working on. :) 
But yeah, I agree with that.
