### ISSUE TITLE
Swap pipenv to another dependency management tool

### ISSUE THREAD

**Issue by joaopslins** [vintasoftware/django-react-boilerplate#377]
Pipenv is not ideal nowadays, probably there are better tools for the job.

Possible candidates:
- pip-tools
- poetry

**Comment by gtsalles** [comment]
My vote is for pip-tools.

**Comment by victorfsf** [comment]
did anyone use poetry in any project before?

**Comment by chocoelho** [comment]
Might be worth taking a look: https://pythonspeed.com/articles/pipenv-docker/
