### ISSUE TITLE
Must set CELERY_TASK_EAGER_PROPAGATES=True in local.py.example

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#38]

**Comment by lucabezerra** [comment]
@fjsj Is this really just adding the setting to the file? Just confirming, in which case we could put the `easy pick` label in it :)

**Comment by fjsj** [comment]
Yes. Thanks @lucabezerra

**Comment by SEdilson** [comment]
@fjsj, wouldn't be more appropriate to set this configuration at local_base.py? To me would make more sense put it in there.

**Comment by fjsj** [comment]
Yes @SEdilson , ideally it would be at local_base.py as well. Thanks
