### ISSUE TITLE
Consider add nginx

### ISSUE THREAD

**Issue by FreelanceDev217** [vintasoftware/django-react-boilerplate#439]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I suggest adding nginx configuration in docker files.

**Comment by joaopslins** [comment]
Hi @FreelanceDev217 , thanks for bringing this up for discussion.

What are your motivations to have nginx on the project? What issue are you trying to solve here?

**Comment by FreelanceDev217** [comment]
I finished a web app development project and found this boiler-plate very useful.
Especially, you have docker files that are almost ready to be used.
I just thought if you add nginx setting (with nginx.conf) in the docker files, it would be more useful.
I am not much experienced and this is just an idea of a newbie.
Thank you anyway for sharing this wonderful boiler-plate.

**Comment by jhgv** [comment]
Hi @FreelanceDev217!
We don't intend for now to add an Nginx pre-configuration file into the boilerplate. However, we are working on a Kubernetes solution that might be helpful if you intend to deploy the boilerplate in any cloud services.

Thanks!
