### ISSUE TITLE
Fix docker make commands that point to backend/manage.py

### ISSUE THREAD

**Issue by vanessa** [vintasoftware/django-react-boilerplate#444]
**Describe the bug**
`dockertest` and `dockertestreset` are the only two commands that run on docker, and they point to `backend/manage.py`, but inside the container it's just `manage.py`.

**To Reproduce**
1. Bootstrap the project with Docker
1. Try to run `make dockertest`
1. Expect error about `backend/manage.py` not being found.

**Expected behavior**
It should find `manage.py` and run the command normally.

**Desktop (please complete the following information):**
Not applicable.

**Additional context**
Not applicable.

**Comment by SEdilson** [comment]
Hi @vanessa, in order to fix this issue i opened the PR #474, the only doubt i had was if it is necessary to update the docs. If so please let me know so i can fix it.

**Comment by vanessa** [comment]
Hi @SEdilson, thanks for the contribution! I'll take a look whenever possible.

**Comment by vanessa** [comment]
Closing because it was solved in #441
