### ISSUE TITLE
Add basic communication between frontend and backend

### ISSUE THREAD

**Issue by vanessa** [vintasoftware/django-react-boilerplate#445]
**Is your feature request related to a problem? Please describe.**
Usually we start the boilerplate with projects we're gonna use with React, and when using the frontend to communicate with the api for POST requests, for example, Django will throw a CSRF missing error.

**Describe the solution you'd like**
Something that could make our job to communicate with the backend from the frontend easier.

**Describe alternatives you've considered**
Maybe install axios and add a wrapper with [interceptors](https://github.com/axios/axios#interceptors) that automatically gets the `csrftoken` from cookies and pass it as the header for "unsafe" requests (`POST`, `PUT`, `PATCH`, etc.), since Django needs it.

I've used something like this and it works:
```js
import axios from "axios";
import cookie from "cookie";

const api = axios.create();
api.interceptors.request.use(config => {
  const { csrftoken } = cookie.parse(document.cookie);
  if (csrftoken) {
    config.headers["X-CSRFTOKEN"] = csrftoken;
  }
  return config;
});
```

**Comment by vanessa** [comment]
@filipeximenes @joaopslins @jhgv Do you guys have any inputs about this?

**Comment by filipeximenes** [comment]
@vanessa love it! I'm all in for the proposed solution.

**Comment by jhgv** [comment]
I think it is a great addition @vanessa

**Comment by joaopslins** [comment]
Great idea!
