### ISSUE TITLE
Remove SASS in favor of Styled Components

### ISSUE THREAD

**Issue by jhgv** [vintasoftware/django-react-boilerplate#451]
**Is your feature request related to a problem? Please describe.**
- Styled components will make the styling of the component more isolated and avoid changes affect more components than it should
- No need to worry about css classes
- Good popularity and documentation

**Describe the solution you'd like**
Replace sass with styled-components

**Comment by vanessa** [comment]
I'm all in for this. @joaopslins any thoughts?

**Comment by joaopslins** [comment]
Yes @vanessa , I think we can proceed with that.

**Comment by fjsj** [comment]
We're moving to react-bootstrap and it uses sass. It doesn't work well with styled-components, so I'm closing this issue: https://stackoverflow.com/questions/45895416/styled-components-and-react-bootstrap
