### ISSUE TITLE
Could not run the Application using the steps

### ISSUE THREAD

**Issue by sandesh2323** [vintasoftware/django-react-boilerplate#456]
- Device: [Lenovo G50]
 - OS: [Ubuntu 16 LTS]
 - Browser [Mozilla ]

I am trying to run the application using the steps given in the setup. I am getting following error from Django side
![Django_erro](https://user-images.githubusercontent.com/46560085/74600724-79c0b400-50bb-11ea-822b-85892ac0b648.png)

Please help.

**Comment by sandesh2323** [comment]
Also Note that my python version is 3.6. Even after changing it to 3.7, same issue is coming. Please confirm if it is code side issue or environmental issue.

**Comment by vanessa** [comment]
Hey @sandesh2323, thanks for getting in touch. From the `ImportError: No module named 'whitenoise'`, it looks like the packages weren't installed in the environment. Do you have the environment enabled to start the server?

**Comment by vanessa** [comment]
@joaopslins Anything you can help with this issue? Is any PyCharm configuration needed beforehand to run our boilerplate?

**Comment by sandesh2323** [comment]
I have solved the problem.. thanks for your help..

**Comment by vanessa** [comment]
Great, thanks. I'm gonna close this issue.
