### ISSUE TITLE
I can't see the webpage on localhost:3000

### ISSUE THREAD

**Issue by jameslee961018** [vintasoftware/django-react-boilerplate#469]
Help me
I can't see this website
I have been installed nom module already 
and I started the npm module but there appeared this sentence "Cannot GET /".
how can i  see the compiled webpage on localhost:3000????
please answer me.
My skype id is live:.cid.d13c000b2004c33
thank you

**Comment by vanessa** [comment]
Hello @jameslee961018, thanks for reaching out.

We use the frontend server (the one that runs on `localhost:3000`) just to serve JavaScript and stylesheet assets so the Django application can use them.

The idea is to run the Django server with `python backend/manage.py runserver` after following the [running steps](https://github.com/vintasoftware/django-react-boilerplate#running), and access the application via `localhost:8000`, there you'll see the correct result.

**Comment by jameslee961018** [comment]
THank you
