### ISSUE TITLE
Can't run make compile_install_requirements on conda environments

### ISSUE THREAD

**Issue by swainsubrat** [vintasoftware/django-react-boilerplate#509]
I'm trying to set up the project in a condo virtual environment, but It is throwing error that no virtual environment is detected.
```
(base) thunderclap@darwin:~/Import Error/import_error$ make compile_install_requirements 
Installing pip-tools...
export PIP_REQUIRE_VIRTUALENV=true; \
pip install pip-tools
ERROR: Could not find an activated virtualenv (required).
Makefile:41: recipe for target 'compile_install_requirements' failed
make: *** [compile_install_requirements] Error 3

```

**Comment by vanessa** [comment]
Hello @swainsubrat, please try to comment out the line below for the time being and execute the command again.

https://github.com/vintasoftware/django-react-boilerplate/blob/master/Makefile#L42

We'll look into this issue whenever possible.
