### ISSUE TITLE
heroku-redis version in app.json throws error

### ISSUE THREAD

**Issue by vanessa** [vintasoftware/django-react-boilerplate#511]
https://github.com/vintasoftware/django-react-boilerplate/blob/c4a203255ce4374bfa2346123a487adb29d877f4/app.json#L49-L51

![image](https://user-images.githubusercontent.com/23136832/84034226-6d18e200-a970-11ea-94b2-d76664a6bf30.png)

**Comment by viv-li** [comment]
+1 am also encountering this issue.

**Comment by vanessa** [comment]
> +1 am also encountering this issue.

Removing the version fixes the issue temporarily.

**Comment by viv-li** [comment]
Yes thank you! That is what I ended up doing. :)
