### ISSUE TITLE
django-webpack-loader is no longer maintained

### ISSUE THREAD

**Issue by tyrozz** [vintasoftware/django-react-boilerplate#527]

**Comment by fjsj** [comment]
Thanks, we're aware and we'll be working on the maintenance of django-webpack-loader.
The original maintainer gave us the permissions and we'll be fixing the main issues in the next few months.

Leaving this open until we get the resolution of the major issues of it.

**Comment by fjsj** [comment]
@rvlb once https://github.com/django-webpack/django-webpack-loader/pull/269 is merged and the version 1.0.0 is launched on PyPI and 1.0.0 on NPM, could you please update django-react-boilerplate and close this issue?
