### ISSUE TITLE
Make collectstatic settings consistent

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#536]
See `app.json`, there's `DISABLE_COLLECTSTATIC` and `ENABLE_DJANGO_COLLECTSTATIC`

**Comment by rvlb** [comment]
This one I want to investigate a bit further because I think `DISABLE_COLLECSTATIC` is specific for Heroku "native" collectstatic, so we have to rely on `ENABLE_DJANGO_COLLECTSTATIC` for running our script.

**Comment by fjsj** [comment]
So I think we should replase `ENABLE_DJANGO_COLLECTSTATIC` with Heroku's default of `DISABLE_COLLECTSTATIC`, because I think `DISABLE_COLLECTSTATIC` is not being used now as we have our own `bin/post_compile`.

**Comment by rvlb** [comment]
So it would be: `DISABLE_COLLECTSTATIC=1`
```bash
# In case we've opted to disable Heroku's default collectstatic, run our own
if [ -f bin/run_collectstatic ] && [ -n "$DISABLE_COLLECTSTATIC" ] && [ "$DISABLE_COLLECTSTATIC" == 1 ]; then
    echo "-----> Running run_collectstatic"
    chmod +x bin/run_collectstatic
    bin/run_collectstatic
fi
```
And there'd be no scenario where we don't run collectstatic (either ours or Heroku's).

**Comment by fjsj** [comment]
I see what you mean. Let's leave as is then.
