### ISSUE TITLE
KeyError 'assets'

### ISSUE THREAD

**Issue by Necro-master** [vintasoftware/django-react-boilerplate#540]
Hi! I followed all README instructions, but it didn't work for me. I got error on the main page:
![Screenshot from 2021-05-16 00-56-25](https://user-images.githubusercontent.com/67829387/118379262-ad9dc880-b5e1-11eb-89b1-2174924d6fa3.png)

How can i fix it?

**Comment by fjsj** [comment]
Hi @Necro-master , I just followed all README instructions and it worked just fine for me.

Could you please provide the following (generated by your project)?
- requirements.txt
- package.json

**Comment by fjsj** [comment]
@Necro-master, please make sure you're using webpack-bundle-tracker@1.0.0 on your `package.json`. Check: https://github.com/django-webpack/django-webpack-loader#migrating-from-version--100

Closing the issue for now, LMK if you still see the issue so I reopen it.
