### ISSUE TITLE
Celery vs click requirement

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#542]
**To Reproduce**
1. Follow the README
2. After `make compile_install_requirements`...
3. see message "celery 5.0.5 requires click<8.0,>=7.0, but you have click 8.0.0 which is incompatible."

**Comment by dmonn** [comment]
`Make sure you have Python 3.8 installed`

Project is not yet Py3.9 compatible it seems. Downgrade fixed this for me

**Comment by hugobessa** [comment]
This has been solved alredy
