### ISSUE TITLE
Fix CircleCI nightly builds

### ISSUE THREAD

**Issue by vanessa** [vintasoftware/django-react-boilerplate#554]
It seems like the deploy key was removed from GitHub, so nightly builds are failing in the checkout step ever since. 

If that's the case, someone with admin access should generate another key and add it to the project. More at: https://discuss.circleci.com/t/git-github-com-permission-denied-publickey-on-repo-that-previously-worked/37763/5

**Comment by fjsj** [comment]
Hi Vanessa, hope all is well. We're having issues with open-source CircleCI in various repos recently. Even when fixing keys, changing permissions, things still fail occasionally (like on external PRs). We want to drop CircleCI entirely and use GH Actions.

I'll try to find time to do this, but we accept PRs too.

**Comment by vanessa** [comment]
Hey, hope all is well too! I can take a stab at moving to Actions if that’s okay.

**Comment by fjsj** [comment]
Yes, sounds great. Please feel free to open a PR, or a draft one if something is not working perfectly.
