### ISSUE TITLE
Remove node_modules and assets from Heroku's slug

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#562]
Depends on https://github.com/vintasoftware/django-react-boilerplate/issues/561

After all files are on S3, it's safe to remove them from Heroku's slug. Use this: https://github.com/vintasoftware/heroku-buildpack-post-build-clean

**Comment by hugobessa** [comment]
We're not supporting Heroku anymore so this has lost its relevance

**Comment by fjsj** [comment]
how the container is generated on Render, though? does it have any ignore paths?
