### ISSUE TITLE
db.sqlite issue:  makemigrations failed

### ISSUE THREAD

**Issue by SeekPoint** [vintasoftware/django-react-boilerplate#586]
**To Reproduce**

.env:
DJANGO_SETTINGS_MODULE=DRBio.settings.local
CELERY_BROKER_URL=amqp://broker:5672//
DATABASE_URL=sqlite:///backend/db.sqlite3

(DRBio-venv) PS C:\DRBio\backend> python manage.py makemigrations
C:\DRBio\DRBio-venv\lib\site-packages\django\core\management\commands\makemigrations.py:105: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': unable to open database file
  warnings.warn(
Migrations for 'users':
  users\migrations\0001_initial.py
    - Create model User
(DRBio-venv) PS C:\DRBio\backend>

**Comment by mathgenius1991712** [comment]
Yes, I got the same issue
Managed to solve it?

**Comment by hugobessa** [comment]
Folks, I wasn't able to reproduce your issue in the current version. I don't know if this got fixed after a recent change. If you're still struggling with this let me know.
