### ISSUE TITLE
Add guide to create DB of sqlite3 and postgrel in readme

### ISSUE THREAD

**Issue by SeekPoint** [vintasoftware/django-react-boilerplate#587]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hugobessa** [comment]
Hey @SeekPoint. If you're using Docker to configure the project the Postgres configuration is already included. If not, we have instructions on how to configure the application with sqlite3. 

The instructions to configure Postgres without Docker would change from OS to OS, so we're not planning to include it.

As this boilerplate recommends Postgres for Production, we also don't plan to have instructions on how to configure sqlite3 on the Docker-based local environment.
