### ISSUE TITLE
Failed at the node-sass@4.14.1 postinstall script.

### ISSUE THREAD

**Issue by OrestisIon** [vintasoftware/django-react-boilerplate#588]
**Describe the bug**
node-sass dependency has a problem.

**To Reproduce**
1. Just download and create using docker

**Expected behavior**
To compile
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hugobessa** [comment]
Hey @OrestisIon, we've recently updated all the frontend dependencies. This problem was probably solved with this update as node-sass isn't even a dependency anymore. 

I'll close this issue, if you still have problems, feel free to reopen or create a new one.
