### ISSUE TITLE
Transform the repository to a template repository

### ISSUE THREAD

**Issue by dennys-bd** [vintasoftware/django-react-boilerplate#596]
This project could use the github feature [Template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) to make it easier to create a new project from it.

That wouldn't necessarily block people from using it through django-admin.
but it would create a much easier alternative and it would make the [Project bootstrap](https://github.com/vintasoftware/django-react-boilerplate#project-bootstrap--) section obsolete in most of cases.

**Comment by pamella** [comment]
After taking the time to explore how [GitHub Template repositories work](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository), I'd like to point out that making the repository a template alone won't completely eliminate the need for running the commands present in the Project Bootstrap section. The Template repository feature primarily streamlines the process of creating a new repository based on a template, but it doesn't address the project-specific configurations handled by the django-admin commands, and users would still need to run the django-admin commands to ensure proper project setup.

I will be closing this issue based on the above considerations. However, please feel free to share your thoughts or discuss any alternative solutions. In case there is a different perspective or workaround that I may have overlooked, let me know. Thank you!
