### ISSUE TITLE
Get reusable methods from django-test-plus

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/django-react-boilerplate#6]
https://github.com/revsys/django-test-plus

**Comment by fjsj** [comment]
Never used. At a quick glance, looks fine. I just wouldn't use the `self.get`, `self.post` because this would break our `self.auth_client`.

IMO we can use this, but we should inherit in our own boilerplate test class and remove `self.get`, `self.post` or other undesired methods to avoid confusion.

**Comment by andersonresende** [comment]
@filipeximenes can we close it?

**Comment by filipeximenes** [comment]
Not much gain if we are not using `self.get`. Let's close.

**Comment by fjsj** [comment]
Used it recently in a toy project. We shouldn't use it, but I think there is some stuff there that we can copy to our TestCase. Reopening.

**Comment by andersonresende** [comment]
This PR https://github.com/vintasoftware/django-react-boilerplate/pull/80 is related to this issue. We can later improve the tests that I have included.
