### ISSUE TITLE
Running make docker_setup returns error with current version of docker-compose.yaml

### ISSUE THREAD

**Issue by bfilipov** [vintasoftware/django-react-boilerplate#604]
Running make docker_setup returns error with current version of docker-compose.yaml
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
volumes.dbdata value Additional properties are not allowed ('name' was unexpected)
make: *** [Makefile:20: docker_setup] Error 1
```
Changing docker-compose version to 3.5 fixes the issue.

**To Reproduce**
1. Clone the project and follow instalation steps.

**Comment by hugobessa** [comment]
@bfilipov what OS are you using? I've just tried to reproduce the issue but wasn't able to. I've opened a PR (#605) for updating the docker-compose version to 3.5 anyway.

**Comment by bfilipov** [comment]
Versions are as follows: 
Docker version 24.0.4, build 3713ee1
Ubuntu 20.04.6 LTS
