### ISSUE TITLE
Celery app name in docker compose appears to not update to project name

### ISSUE THREAD

**Issue by BrendanJM** [vintasoftware/django-react-boilerplate#660]
**Describe the bug**
Celery app name is not templated: https://github.com/vintasoftware/django-react-boilerplate/blob/97c1f4f08d4e0f323845a9cdd789a7927c10428a/docker-compose.yml#L52

**To Reproduce**
See link above

**Expected behavior**
It should be templated to `{{project_name}}` vs `myproject`

**Comment by fjsj** [comment]
thanks, good catch, we'll check all occurrences for myproject
