### ISSUE TITLE
psycopg2 is no longer recommended for new Django projects 

### ISSUE THREAD

**Issue by BrendanJM** [vintasoftware/django-react-boilerplate#661]
**Is your feature request related to a problem? Please describe.**
`psycopg2` is [no longer recommended](https://docs.djangoproject.com/en/5.0/ref/databases/#postgresql-notes) for Django. 

**Describe the solution you'd like**
- Evaluate and update to `psycopg` (aka `psycopg3`) as appropriate

**Comment by fjsj** [comment]
Thanks for the heads up! We'll update ASAP.
